import {
  Asset,
  Zone,
  QuotationRequest,
  SparePart,
  Shorebase,
  Vendor,
  Tender,
  MaintenanceRecord,
} from "./types";

// Dynamic Date Helper
const currentYear = new Date().getFullYear();
const nextYear = currentYear + 1;
const today = new Date().toISOString().split("T")[0];

export const vendors: Vendor[] = [
  {
    id: "v-001",
    name: "PT. Samudra Merah Putih",
    type: "PT",
    status: "Verified",
    npwp: "01.234.567.8-123.000",
    civilRegistrationType: "National",
    address: "Jl. Sudirman No. 45, Jakarta",
    phone: "+62 21 575 8888",
    civdId: "CIVD-00123",
    civdExpiry: `${nextYear}-05-20`,
    csmsScore: 95,
    performanceRating: 4.9,
    projectsCompleted: 24,
    riskLevel: "Low",
    contactName: "Budi Santoso",
    contactEmail: "bids@samudrahmerah.co.id",
  },
  {
    id: "v-002",
    name: "Global Offshore Indonesia",
    type: "PT",
    status: "Verified",
    npwp: "02.345.678.9-234.000",
    civilRegistrationType: "Local",
    address: "Jl. Diponegoro No. 10, Surabaya",
    phone: "+62 31 550 1234",
    civdId: "CIVD-00456",
    civdExpiry: `${currentYear}-12-15`,
    csmsScore: 88,
    performanceRating: 4.5,
    projectsCompleted: 12,
    riskLevel: "Low",
    contactName: "Sarah Wijaya",
    contactEmail: "ops@globaloffshore.id",
  },
  {
    id: "v-003",
    name: "Deepsea Drilling Intl",
    type: "BUT",
    status: "Verified",
    npwp: "03.456.789.0-345.000",
    civilRegistrationType: "National",
    address: "Menara Karya Lt. 22, Jakarta",
    phone: "+62 21 520 9999",
    civdId: "CIVD-00789",
    civdExpiry: `${currentYear}-08-01`,
    csmsScore: 75,
    performanceRating: 3.8,
    projectsCompleted: 8,
    riskLevel: "Medium",
    contactName: "Michael Johnson",
    contactEmail: "tender@deepseadrill.com",
  },
  {
    id: "v-004",
    name: "PT. Maju Mundur Kena",
    type: "PT",
    status: "Blacklisted",
    npwp: "99.999.999.9-999.000",
    civilRegistrationType: "Local",
    address: "Jl. Buntu No. 0, Nowhere",
    phone: "+62 00 000 0000",
    civdId: "CIVD-SUSPEND",
    civdExpiry: "2023-01-01",
    csmsScore: 40,
    performanceRating: 1.5,
    projectsCompleted: 2,
    riskLevel: "High",
    contactName: "Unknown",
    contactEmail: "admin@majumundur.co.id",
  },
];

export const shorebases: Shorebase[] = [
  {
    id: "sb1",
    name: "Pangkalan Matak (Anambas)",
    location: "Kepulauan Anambas",
    coordinates: { lat: 3.54, lng: 106.26 },
    capabilities: [
      "Fuel Bunkering",
      "Open Yard",
      "Helipad",
      "Waste Management",
    ],
    currentStock: [
      { item: "Minyak Solar (MGO)", qty: 500000, unit: "Liter" },
      { item: "Pipa Bor 5 inch", qty: 450, unit: "Joint" },
      { item: "Barite (Lumpur)", qty: 2000, unit: "Sak" },
    ],
    owner: "Medco Energi",
    type: "KKKS",
  },
  {
    id: "sb2",
    name: "Lamongan Shorebase",
    location: "Jawa Timur",
    coordinates: { lat: -6.89, lng: 112.3 },
    capabilities: ["Heavy Lift Crane", "Warehouse"],
    currentStock: [
      { item: "Pipa Tubular", qty: 5000, unit: "MT" },
      { item: "Unit Semen (Cementing)", qty: 4, unit: "Unit" },
    ],
    owner: "East Log",
    type: "ThirdParty",
  },
  {
    id: "sb3",
    name: "Hub Logistik Sorong",
    location: "Papua Barat",
    coordinates: { lat: -0.87, lng: 131.25 },
    capabilities: ["Deep Water Jetty", "Drilling Mud Plant"],
    currentStock: [{ item: "Minyak Solar (MGO)", qty: 100000, unit: "Liter" }],
    owner: "Pertamina EP",
    type: "KKKS",
  },
];

export const assets: Asset[] = [
  {
    id: "1",
    number: "RG-2023-001",
    name: "Rig Darat A (Onshore)",
    category: "Onshore Rig",
    subType: "Land Rig",
    location: "Riau, WK Rokan",
    coordinates: { lat: 1.5, lng: 101.5 },
    history: [{ lat: 1.5, lng: 101.5 }],
    dailyRate: 250000000,
    status: "Active",
    health: 98,
    csmsScore: 92,
    incidentCount: 0,
    daysSinceIncident: 365,
    yearBuilt: 2018,
    manufacturer: "National Oilwell Varco",
    flagCountry: "Indonesia",
    ownerType: "National",
    ownerVendorId: "v-001",
    certification: "BKI Class",
    capacityString: "2000 HP / 25000 ft",
    specs: {
      ratedHP: 2000,
      drillingDepth: 25000,
    },
    co2Emissions: 12.5,
    totalEmissions: 1200,
    nextMaintenanceDate: `${nextYear}-01-15`,
    mtbf: 5000,
    inventory: [
      {
        id: "sp-1",
        name: "Hydraulic Valve Set",
        sku: "HVS-001",
        category: "Hydraulics",
        quantity: 5,
        minLevel: 2,
        unit: "Set",
        location: "Warehouse A",
        lastUpdated: today,
      },
    ],
    maintenanceLog: [],
  },
  {
    id: "2",
    number: "VS-2022-045",
    name: "Vessel B (AHTS)",
    category: "Kapal",
    subType: "AHTS",
    location: "Laut Jawa",
    coordinates: { lat: -5.5, lng: 107.5 },
    history: [{ lat: -5.5, lng: 107.5 }],
    dailyRate: 150000000,
    status: "Active",
    health: 95,
    csmsScore: 88,
    incidentCount: 0,
    daysSinceIncident: 120,
    yearBuilt: 2015,
    manufacturer: "Damen Shipyards",
    flagCountry: "Indonesia",
    ownerType: "National",
    ownerVendorId: "v-002",
    dataOwner: {
      name: "PT. Pelayaran Nasional Indonesia",
      email: "ops@pelni.co.id",
      phone: "+62 21 633 4342",
      address: "Jl. Gajah Mada No. 14, Jakarta Pusat",
      type: "Owner",
      proofOfOwnershipDoc: "docs/ownership_vsl001.pdf",
    },
    certification: "BKI Class",
    capacityString: "80 Ton BP / 5000 DWT",
    specs: {
      bollardPull: 80,
      dwt: 5000,
      maxSpeed: 12,
      loa: 65,
      breadth: 16,
      depth: 6,
      draft: 5,
      // Gap Fix: Detailed Specs
      capacities: {
        fuelOil: 500,
        freshWater: 200,
        deckArea: 300,
        deckCargo: 500,
      },
      fireFighting: {
        class: "FiFi 1",
        monitors: 2,
        capacity: 2400,
      },
      navigation: {
        radar: ["Furuno X-Band"],
        gps: "Furuno GP-170",
        echoSounder: "FE-800",
        autoPilot: "Simrad AP70",
        gmdss: "Area 3",
        ais: true,
      },
    },
    co2Emissions: 8.2,
    totalEmissions: 800,
    nextMaintenanceDate: `${currentYear}-11-20`,
    mtbf: 4000,
    imoNumber: "9781234",
    inventory: [
      {
        id: "sp-2",
        name: "Synthetic Oil (55 Gal)",
        sku: "OIL-SYN-55",
        category: "Lubricants",
        quantity: 10,
        minLevel: 5,
        unit: "Drum",
        location: "Engine Room Store",
        lastUpdated: today,
      },
    ],
    maintenanceLog: [],
  },
  {
    id: "3",
    number: "RG-OFF-009",
    name: "Rig Lepas Pantai C (Jack-up)",
    category: "Offshore Rig",
    subType: "Jack-up",
    location: "Laut Natuna Utara",
    coordinates: { lat: 4.5, lng: 108.0 },
    history: [{ lat: 4.5, lng: 108.0 }],
    dailyRate: 1200000000,
    status: "Active",
    health: 92,
    csmsScore: 90,
    incidentCount: 0,
    daysSinceIncident: 500,
    yearBuilt: 2012,
    manufacturer: "Keppel FELS",
    flagCountry: "Panama",
    ownerType: "Foreign",
    ownerVendorId: "v-003",
    dataOwner: {
      name: "Global Offshore Drilling Ltd.",
      email: "contracts@global-offshore.com",
      phone: "+1 713 555 0199",
      address: "12 Greenway Plaza, Houston, TX",
      type: "Operator",
      appointmentEndDate: "2026-12-31",
      appointmentDoc: "docs/appt_rig009_signed.pdf",
      proofOfOwnershipDoc: "docs/ownership_rig009.pdf",
    },
    certification: "ABS / BKI Dual Class",
    capacityString: "3000 HP / 400 ft Water Depth",
    specs: {
      ratedHP: 3000,
      drillingDepth: 30000,
      waterDepth: 400,
      quartersCapacity: 120,
      variableDeckLoad: 5000,
      // Gap Fix: Detailed Rig Specs
      drawworksHP: 3000,
      topDriveTorque: 50000,
      mudSystem: {
        pumpCount: 3,
        pumpType: "National 12-P-160",
        pressureRating: 5000,
        totalCapacity: 3500,
        shaleShakers: 4,
        desander: true,
        desilter: true,
      },
      wellControl: {
        bopStack: "13-5/8 10k",
        diverter: "21-1/4 500psi",
        chokeManifold: "10k psi",
        accumulatorUnit: "Standard",
      },
    },
    co2Emissions: 25.0,
    totalEmissions: 5000,
    nextMaintenanceDate: `${currentYear}-10-01`,
    mtbf: 8000,
    inventory: [
      {
        id: "sp-3",
        name: "Diesel Filter (Main)",
        sku: "FIL-DSL-001",
        category: "Filters",
        quantity: 20,
        minLevel: 10,
        unit: "Pcs",
        location: "Store B",
        lastUpdated: today,
      },
    ],
    maintenanceLog: [],
  },
  // NEW ASSETS FOR WORKFLOW DEMO
  {
    id: "4",
    number: "VS-PENDING-001",
    name: "Bintang Laut 01",
    category: "Kapal",
    subType: "Crewboat",
    location: "Batam (Dockyard)",
    coordinates: { lat: 1.1, lng: 104.0 },
    history: [],
    dailyRate: 0,
    status: "Registered",
    health: 100,
    csmsScore: 0,
    incidentCount: 0,
    daysSinceIncident: 0,
    yearBuilt: 2023,
    manufacturer: "Batam Shipyard",
    flagCountry: "Indonesia",
    ownerType: "National",
    ownerVendorId: "v-002", // Global Offshore
    certification: "Pending BKI",
    capacityString: "Pending Specs",
    specs: {},
    co2Emissions: 0,
    totalEmissions: 0,
    nextMaintenanceDate: "",
    mtbf: 0,
  },
  {
    id: "5",
    number: "RG-VERIFY-002",
    name: "Rig Semeru 05",
    category: "Onshore Rig",
    subType: "Workover",
    location: "Cepu Block",
    coordinates: { lat: -7.15, lng: 111.6 },
    history: [],
    dailyRate: 150000000,
    status: "Verification",
    health: 100,
    csmsScore: 85,
    incidentCount: 0,
    daysSinceIncident: 0,
    yearBuilt: 2020,
    manufacturer: "RG Petro-Machinery",
    flagCountry: "Indonesia",
    ownerType: "National",
    ownerVendorId: "v-001", // Samudra Merah Putih
    certification: "Migas SKPP (Submitted)",
    capacityString: "750 HP / 10000 ft",
    specs: {
      ratedHP: 750,
      drillingDepth: 10000,
    },
    co2Emissions: 0,
    totalEmissions: 0,
    nextMaintenanceDate: "",
    mtbf: 0,
  },
  {
    id: "6",
    number: "VS-CAT-003",
    name: "Ocean Tug 99",
    category: "Kapal",
    subType: "Tugboat",
    location: "Surabaya",
    coordinates: { lat: -7.2, lng: 112.75 },
    history: [],
    dailyRate: 0,
    status: "Catalog_Filling",
    health: 100,
    csmsScore: 0,
    incidentCount: 0,
    daysSinceIncident: 0,
    yearBuilt: 2019,
    manufacturer: "PAL Indonesia",
    flagCountry: "Indonesia",
    ownerType: "National",
    ownerVendorId: "v-002",
    certification: "BKI",
    capacityString: "40 Ton BP",
    specs: {
      bollardPull: 40,
    },
    co2Emissions: 0,
    totalEmissions: 0,
    nextMaintenanceDate: "",
    mtbf: 0,
  },
  {
    id: "7",
    number: "RG-CRIT-007",
    name: "Rig Delta (Maintenance)",
    category: "Offshore Rig",
    subType: "Semi-Sub",
    location: "Selat Makassar",
    coordinates: { lat: -2.5, lng: 118.5 },
    history: [],
    dailyRate: 0,
    status: "Maintenance",
    health: 45, // Low health triggers pulse
    csmsScore: 60,
    incidentCount: 2,
    daysSinceIncident: 5,
    yearBuilt: 2010,
    manufacturer: "Samsung Heavy Ind",
    flagCountry: "South Korea",
    ownerType: "Foreign",
    ownerVendorId: "v-003",
    certification: "Expired",
    capacityString: "5000 ft WD",
    specs: {},
    co2Emissions: 15,
    totalEmissions: 500,
    nextMaintenanceDate: "Overdue",
    mtbf: 1000,
  },
  {
    id: "8",
    number: "RG-2023-015",
    name: "Rig Semesta 01",
    category: "Onshore Rig",
    subType: "Land Rig",
    location: "Jambi Merang",
    coordinates: { lat: -2.0, lng: 103.5 },
    history: [],
    dailyRate: 180000000,
    status: "Active",
    health: 96,
    csmsScore: 89,
    incidentCount: 0,
    daysSinceIncident: 200,
    yearBuilt: 2017,
    manufacturer: "RG Petro",
    flagCountry: "Indonesia",
    ownerType: "National",
    ownerVendorId: "v-001",
    certification: "BKI",
    capacityString: "1500 HP",
    specs: {},
    co2Emissions: 10,
    totalEmissions: 900,
    nextMaintenanceDate: "2024-12-01",
    mtbf: 4000,
  },
  {
    id: "9",
    number: "VS-2020-112",
    name: "Vessel C (Supply)",
    category: "Kapal",
    subType: "Supply Vessel",
    location: "Laut Jawa Timur",
    coordinates: { lat: -6.5, lng: 113.0 },
    history: [],
    dailyRate: 90000000,
    status: "Active",
    health: 99,
    csmsScore: 94,
    incidentCount: 0,
    daysSinceIncident: 450,
    yearBuilt: 2020,
    manufacturer: "Vard",
    flagCountry: "Indonesia",
    ownerType: "National",
    ownerVendorId: "v-002",
    certification: "BKI",
    capacityString: "3000 DWT",
    specs: {},
    co2Emissions: 6,
    totalEmissions: 400,
    nextMaintenanceDate: "2025-06-15",
    mtbf: 6000,
  },
  {
    id: "10",
    number: "RG-OFF-088",
    name: "Deepwater Horizon II",
    category: "Offshore Rig",
    subType: "Drillship",
    location: "Selat Makassar (Transit)",
    coordinates: { lat: -3.5, lng: 118.0 },
    history: [
      { lat: -3.4, lng: 118.0 },
      { lat: -3.3, lng: 118.1 },
    ],
    dailyRate: 2500000000,
    status: "Active",
    health: 88,
    csmsScore: 95,
    incidentCount: 0,
    daysSinceIncident: 1000,
    yearBuilt: 2019,
    manufacturer: "Samsung",
    flagCountry: "Marshall Islands",
    ownerType: "Foreign",
    ownerVendorId: "v-003",
    certification: "ABS",
    capacityString: "12000 ft WD",
    specs: {},
    co2Emissions: 35,
    totalEmissions: 8000,
    nextMaintenanceDate: "2024-09-01",
    mtbf: 9000,
  },
  {
    id: "11",
    number: "VS-TUG-009",
    name: "Harbour Tug 09",
    category: "Kapal",
    subType: "Tugboat",
    location: "Balikpapan",
    coordinates: { lat: -1.25, lng: 116.8 },
    history: [],
    dailyRate: 40000000,
    status: "Inactive",
    health: 75,
    csmsScore: 80,
    incidentCount: 1,
    daysSinceIncident: 30,
    yearBuilt: 2005,
    manufacturer: "Local Yard",
    flagCountry: "Indonesia",
    ownerType: "National",
    ownerVendorId: "v-001",
    certification: "BKI (Expired)",
    capacityString: "30 Ton BP",
    specs: {},
    co2Emissions: 5,
    totalEmissions: 200,
    nextMaintenanceDate: "Overdue",
    mtbf: 2000,
  },
  // --- SUMATRA OPERATIONAL AREA (ROKAN & JAMBI) ---
  {
    id: "12",
    number: "RG-ONS-101",
    name: "Rig Harimau 01",
    category: "Onshore Rig",
    subType: "Land Rig",
    location: "Duri Field, Riau",
    coordinates: { lat: 1.25, lng: 101.2 },
    history: [
      { lat: 1.25, lng: 101.2 },
      { lat: 1.24, lng: 101.21 },
      { lat: 1.26, lng: 101.19 },
    ],
    dailyRate: 150000000,
    status: "Active",
    health: 95,
    csmsScore: 88,
    incidentCount: 0,
    daysSinceIncident: 400,
    yearBuilt: 2015,
    manufacturer: "NOV",
    ownerType: "National",
    certification: "SKPP",
    capacityString: "1000 HP",
    specs: {
      ratedHP: 1000,
      drillingDepth: 12000,
      drawworksHP: 1100,
      topDriveTorque: 35000,
      mudSystem: {
        pumpCount: 2,
        pumpType: "Triplex 1600 HP",
        pressureRating: 5000,
        totalCapacity: 2000,
        shaleShakers: 3,
        desander: true,
        desilter: true,
      },
    },
    co2Emissions: 8,
    totalEmissions: 600,
    nextMaintenanceDate: "2024-08-10",
    mtbf: 2500,
    inventory: [
      {
        id: "sp-12-1",
        name: "Drill Pipe 5 inch",
        sku: "DP-500",
        category: "Drilling",
        quantity: 200,
        minLevel: 50,
        unit: "Joint",
        location: "Pipe Rack",
        lastUpdated: "2024-01-01",
      },
    ],
  },
  {
    id: "13",
    number: "RG-ONS-102",
    name: "Rig Harimau 02",
    category: "Onshore Rig",
    subType: "Workover Rig",
    location: "Minas Field, Riau",
    coordinates: { lat: 0.85, lng: 101.4 },
    history: [
      { lat: 0.85, lng: 101.4 },
      { lat: 0.88, lng: 101.42 },
    ],
    dailyRate: 120000000,
    status: "Active",
    health: 92,
    csmsScore: 90,
    incidentCount: 0,
    daysSinceIncident: 150,
    yearBuilt: 2016,
    manufacturer: "RG Petro",
    ownerType: "National",
    certification: "SKPP",
    capacityString: "750 HP",
    specs: {
      ratedHP: 750,
      drillingDepth: 8000,
      mudSystem: {
        pumpCount: 2,
        pumpType: "Triplex",
        pressureRating: 3500,
        totalCapacity: 1000,
        shaleShakers: 2,
        desander: true,
        desilter: false,
      },
    },
    co2Emissions: 5,
    totalEmissions: 300,
    nextMaintenanceDate: "2024-09-01",
    mtbf: 3000,
    inventory: [
      {
        id: "sp-13-1",
        name: "Tubing 2-7/8",
        sku: "TBG-278",
        category: "Tubulars",
        quantity: 300,
        minLevel: 50,
        unit: "Joint",
        location: "Pipe Rack",
        lastUpdated: "2024-01-15",
      },
    ],
  },
  {
    id: "14",
    number: "RG-ONS-105",
    name: "Rig Andalas X",
    category: "Onshore Rig",
    subType: "Land Rig",
    location: "Jambi Merang Block",
    coordinates: { lat: -1.9, lng: 103.8 },
    history: [
      { lat: -1.9, lng: 103.8 },
      { lat: -1.95, lng: 103.85 },
    ],
    dailyRate: 175000000,
    status: "Maintenance",
    health: 60,
    csmsScore: 85,
    incidentCount: 0,
    daysSinceIncident: 80,
    yearBuilt: 2014,
    manufacturer: "China Oilfield",
    ownerType: "National",
    certification: "SKPP",
    capacityString: "1500 HP",
    specs: {
      ratedHP: 1500,
      drillingDepth: 18000,
      drawworksHP: 2000,
      topDriveTorque: 50000,
    },
    co2Emissions: 9,
    totalEmissions: 750,
    nextMaintenanceDate: "In Progress",
    mtbf: 2000,
    inventory: [
      {
        id: "sp-14-1",
        name: "Engine Parts",
        sku: "ENG-099",
        category: "Engine",
        quantity: 5,
        minLevel: 2,
        unit: "Box",
        location: "Warehouse",
        lastUpdated: "2023-12-12",
      },
    ],
  },

  // --- JAVA SEA (ONWJ & EAST JAVA) ---
  {
    id: "15",
    number: "VS-AHTS-88",
    name: "Java Star III",
    category: "Kapal",
    subType: "AHTS",
    location: "ONWJ Block",
    coordinates: { lat: -5.9, lng: 107.8 },
    history: [
      { lat: -5.9, lng: 107.8 },
      { lat: -5.92, lng: 107.82 },
      { lat: -5.88, lng: 107.78 },
    ],
    dailyRate: 85000000,
    status: "Active",
    health: 98,
    csmsScore: 92,
    incidentCount: 0,
    daysSinceIncident: 600,
    yearBuilt: 2018,
    manufacturer: "Batam Yard",
    ownerType: "National",
    certification: "BKI",
    capacityString: "60 Ton BP",
    specs: {
      bollardPull: 60,
      bhp: 5000,
      maxSpeed: 12,
      grossTonnage: 1200,
      capacities: {
        fuelOil: 500,
        freshWater: 200,
        deckArea: 150,
        deckCargo: 300,
        bulkCement: 100,
        drillWater: 400,
        liquidMud: 250,
      },
      navigation: {
        radar: ["Furuno X-Band"],
        gps: "Furuno GP-170",
        echoSounder: "Skipper",
        autoPilot: "Simrad",
        gmdss: "A3",
        ais: true,
      },
    },
    co2Emissions: 7,
    totalEmissions: 500,
    nextMaintenanceDate: "2025-01-01",
    mtbf: 5000,
    inventory: [
      {
        id: "sp-15-1",
        name: "Fuel Filter",
        sku: "FLT-001",
        category: "Engine",
        quantity: 20,
        minLevel: 5,
        unit: "Pcs",
        location: "Engine Room",
        lastUpdated: "2024-02-01",
      },
    ],
  },
  {
    id: "16",
    number: "VS-CB-22",
    name: "Fast Crew 05",
    category: "Kapal",
    subType: "Crewboat",
    location: "Offshore Madura",
    coordinates: { lat: -7.3, lng: 113.2 },
    history: [
      { lat: -7.3, lng: 113.2 },
      { lat: -7.2, lng: 113.3 },
      { lat: -7.1, lng: 113.25 },
    ],
    dailyRate: 35000000,
    status: "Active",
    health: 99,
    csmsScore: 95,
    incidentCount: 0,
    daysSinceIncident: 300,
    yearBuilt: 2021,
    manufacturer: "Penguin",
    ownerType: "National",
    certification: "BKI",
    capacityString: "50 Pax",
    specs: {
      maxSpeed: 25,
      grossTonnage: 200,
      loa: 30,
      breadth: 8,
      mainEngine: "Caterpillar C32",
      bhp: 3000,
    },
    co2Emissions: 2,
    totalEmissions: 100,
    nextMaintenanceDate: "2024-11-20",
    mtbf: 1000,
    inventory: [
      {
        id: "sp-16-1",
        name: "Oil Filter",
        sku: "CAT-FILT",
        category: "Engine",
        quantity: 10,
        minLevel: 2,
        unit: "Pcs",
        location: "Store",
        lastUpdated: "2024-03-01",
      },
    ],
  },
  {
    id: "17",
    number: "RG-OFF-55",
    name: "Rig Java Pride",
    category: "Offshore Rig",
    subType: "Jack-up",
    location: "West Madura Offshore",
    coordinates: { lat: -6.8, lng: 112.9 },
    history: [
      { lat: -6.8, lng: 112.9 },
      { lat: -6.78, lng: 112.92 },
    ],
    dailyRate: 900000000,
    status: "Active",
    health: 90,
    csmsScore: 88,
    incidentCount: 0,
    daysSinceIncident: 250,
    yearBuilt: 2011,
    manufacturer: "Keppel",
    ownerType: "Foreign",
    certification: "ABS",
    capacityString: "350 ft WD",
    specs: {
      ratedHP: 3000,
      drillingDepth: 25000,
      waterDepth: 350,
      cantileverSkid: 70,
      quartersCapacity: 120,
      variableDeckLoad: 6000,
    },
    co2Emissions: 22,
    totalEmissions: 4000,
    nextMaintenanceDate: "2024-10-15",
    mtbf: 6000,
    inventory: [
      {
        id: "sp-17-1",
        name: "Casing 13-3/8",
        sku: "CSG-1338",
        category: "Tubulars",
        quantity: 50,
        minLevel: 10,
        unit: "Joint",
        location: "Pipe Deck",
        lastUpdated: "2023-11-20",
      },
    ],
  },

  // --- KALIMANTAN (MAHAKAM & MAKASSAR STRAIT) ---
  {
    id: "18",
    number: "VS-ACC-01",
    name: "Mahakam Support 01",
    category: "Kapal",
    subType: "Accommodation Barge",
    location: "Mahakam Delta",
    coordinates: { lat: -0.8, lng: 117.4 },
    history: [
      { lat: -0.8, lng: 117.4 },
      { lat: -0.78, lng: 117.45 },
    ],
    dailyRate: 150000000,
    status: "Active",
    health: 94,
    csmsScore: 91,
    incidentCount: 0,
    daysSinceIncident: 400,
    yearBuilt: 2013,
    manufacturer: "Local",
    ownerType: "National",
    certification: "BKI",
    capacityString: "200 Pax",
    specs: {
      grossTonnage: 3500,
      loa: 75,
      breadth: 20,
      capacities: {
        freshWater: 600,
        fuelOil: 400,
        deckArea: 500,
        deckCargo: 100,
        bulkCement: 0,
      },
    },
    co2Emissions: 12,
    totalEmissions: 1500,
    nextMaintenanceDate: "2024-12-10",
    mtbf: 4000,
    inventory: [
      {
        id: "sp-18-1",
        name: "Kitchen Supplies",
        sku: "KITCH-001",
        category: "Provisions",
        quantity: 50,
        minLevel: 10,
        unit: "Box",
        location: "Mess Hall",
        lastUpdated: "2024-01-20",
      },
    ],
  },
  {
    id: "19",
    number: "RG-SWAMP-03",
    name: "Rig Rawa 03",
    category: "Onshore Rig",
    subType: "Swamp Barge",
    location: "Tunu Field",
    coordinates: { lat: -0.6, lng: 117.3 },
    history: [
      { lat: -0.6, lng: 117.3 },
      { lat: -0.58, lng: 117.32 },
    ],
    dailyRate: 300000000,
    status: "Active",
    health: 89,
    csmsScore: 93,
    incidentCount: 0,
    daysSinceIncident: 120,
    yearBuilt: 2009,
    manufacturer: "Apexindo",
    ownerType: "National",
    certification: "BKI",
    capacityString: "Swamp Rig",
    specs: {
      ratedHP: 1500,
      drillingDepth: 15000,
      cantileverSkid: 40,
      quartersCapacity: 80,
    },
    co2Emissions: 18,
    totalEmissions: 2500,
    nextMaintenanceDate: "2025-02-01",
    mtbf: 3500,
    inventory: [
      {
        id: "sp-19-1",
        name: "Mud Pump Liner",
        sku: "PUMP-LNR",
        category: "Drilling",
        quantity: 12,
        minLevel: 4,
        unit: "Pcs",
        location: "Store 1",
        lastUpdated: "2024-02-10",
      },
    ],
  },
  {
    id: "20",
    number: "VS-OSV-99",
    name: "Strait Supplier",
    category: "Kapal",
    subType: "PSV",
    location: "Selat Makassar (North)",
    coordinates: { lat: 0.5, lng: 118.2 },
    history: [
      { lat: 0.5, lng: 118.2 },
      { lat: 0.6, lng: 118.3 },
      { lat: 0.7, lng: 118.4 },
    ],
    dailyRate: 110000000,
    status: "Active",
    health: 97,
    csmsScore: 96,
    incidentCount: 0,
    daysSinceIncident: 800,
    yearBuilt: 2019,
    manufacturer: "Vard",
    ownerType: "Foreign",
    certification: "DNV",
    capacityString: "4000 DWT",
    specs: {
      dwt: 4000,
      grossTonnage: 3200,
      loa: 85,
      breadth: 18,
      bollardPull: 0, // PSV usually not rated for BP
      capacities: {
        fuelOil: 800,
        freshWater: 600,
        liquidMud: 800,
        bulkCement: 300,
        deckArea: 750,
        deckCargo: 1500,
      },
    },
    co2Emissions: 10,
    totalEmissions: 2000,
    nextMaintenanceDate: "2025-05-05",
    mtbf: 7000,
    inventory: [
      {
        id: "sp-20-1",
        name: "Valve Control",
        sku: "VLV-CTRL",
        category: "Deck",
        quantity: 5,
        minLevel: 1,
        unit: "Unit",
        location: "E-Room",
        lastUpdated: "2024-01-05",
      },
    ],
  },

  // --- EASTERN INDONESIA (PAPUA & MALUKU) ---
  {
    id: "21",
    number: "VS-LNG-01",
    name: "Tangguh Carrier I",
    category: "Kapal",
    subType: "LNG Tanker",
    location: "Teluk Bintuni",
    coordinates: { lat: -2.3, lng: 133.1 },
    history: [
      { lat: -2.3, lng: 133.1 },
      { lat: -2.2, lng: 133.0 },
      { lat: -2.1, lng: 132.9 },
    ],
    dailyRate: 500000000,
    status: "Active",
    health: 99,
    csmsScore: 98,
    incidentCount: 0,
    daysSinceIncident: 1500,
    yearBuilt: 2020,
    manufacturer: "Hyundai HI",
    ownerType: "Foreign",
    certification: "DNV",
    capacityString: "150,000 m3",
    specs: {
      dwt: 90000,
      grossTonnage: 110000,
      loa: 280,
      breadth: 45,
      maxSpeed: 18,
      capacities: {
        fuelOil: 5000,
        freshWater: 1000,
        deckArea: 0,
        deckCargo: 0,
        bulkCement: 0,
      },
    },
    co2Emissions: 45,
    totalEmissions: 12000,
    nextMaintenanceDate: "2025-10-01",
    mtbf: 15000,
    inventory: [
      {
        id: "sp-21-1",
        name: "Cryogenic Valve",
        sku: "CRYO-VLV",
        category: "Cargo",
        quantity: 2,
        minLevel: 1,
        unit: "Unit",
        location: "Cargo Hold",
        lastUpdated: "2024-03-10",
      },
    ],
  },
  {
    id: "22",
    number: "VS-AHTS-TS",
    name: "Timor Supporter",
    category: "Kapal",
    subType: "AHTS",
    location: "Arafura Sea (Masela)",
    coordinates: { lat: -8.8, lng: 130.2 },
    history: [
      { lat: -8.8, lng: 130.2 },
      { lat: -8.82, lng: 130.22 },
    ],
    dailyRate: 100000000,
    status: "Active",
    health: 93,
    csmsScore: 90,
    incidentCount: 0,
    daysSinceIncident: 330,
    yearBuilt: 2016,
    manufacturer: "Nantong",
    ownerType: "National",
    certification: "BKI",
    capacityString: "100 Ton BP",
    specs: {
      bollardPull: 100,
      bhp: 8000,
      maxSpeed: 14,
      dwt: 3000,
      grossTonnage: 2500,
    },
    co2Emissions: 9,
    totalEmissions: 900,
    nextMaintenanceDate: "2024-11-01",
    mtbf: 4500,
    inventory: [
      {
        id: "sp-22-1",
        name: "Tow Wire",
        sku: "WIRE-TOW",
        category: "Deck",
        quantity: 2,
        minLevel: 1,
        unit: "Reel",
        location: "Aft Deck",
        lastUpdated: "2024-01-01",
      },
    ],
  },
  {
    id: "23",
    number: "RG-SOR-01",
    name: "Rig Salawati",
    category: "Onshore Rig",
    subType: "Land Rig",
    location: "Sorong (Salawati)",
    coordinates: { lat: -1.0, lng: 131.1 },
    history: [
      { lat: -1.0, lng: 131.1 },
      { lat: -1.02, lng: 131.12 },
    ],
    dailyRate: 140000000,
    status: "Active",
    health: 88,
    csmsScore: 85,
    incidentCount: 1,
    daysSinceIncident: 60,
    yearBuilt: 2010,
    manufacturer: "RG Petro",
    ownerType: "National",
    certification: "SKPP",
    capacityString: "1000 HP",
    specs: {
      ratedHP: 1000,
      drillingDepth: 10000,
      mudSystem: {
        pumpCount: 2,
        pumpType: "Triplex",
        pressureRating: 5000,
        totalCapacity: 1200,
        shaleShakers: 2,
        desander: true,
        desilter: true,
      },
    },
    co2Emissions: 11,
    totalEmissions: 1000,
    nextMaintenanceDate: "2024-08-30",
    mtbf: 2200,
    inventory: [
      {
        id: "sp-23-1",
        name: "BOP Ram",
        sku: "BOP-RAM",
        category: "Well Control",
        quantity: 4,
        minLevel: 2,
        unit: "Set",
        location: "BOP Stack",
        lastUpdated: "2024-02-15",
      },
    ],
  },

  // --- NATUNA EXPANSION ---
  {
    id: "24",
    number: "VS-PATROL-01",
    name: "Natuna Patrol 01",
    category: "Kapal",
    subType: "Patrol Vessel",
    location: "North Natuna Border",
    coordinates: { lat: 6.1, lng: 107.8 }, // Far north
    history: [
      { lat: 6.1, lng: 107.8 },
      { lat: 6.0, lng: 107.7 },
      { lat: 5.9, lng: 107.8 },
    ],
    dailyRate: 45000000,
    status: "Active",
    health: 96,
    csmsScore: 92,
    incidentCount: 0,
    daysSinceIncident: 365,
    yearBuilt: 2018,
    manufacturer: "Palindo",
    ownerType: "National",
    certification: "BKI",
    capacityString: "60m Fast Boat",
    specs: {
      maxSpeed: 35,
      grossTonnage: 400,
      loa: 60,
      breadth: 9,
      mainEngine: "MTU 4000",
      bhp: 6000,
    },
    co2Emissions: 5,
    totalEmissions: 300,
    nextMaintenanceDate: "2025-02-15",
    mtbf: 3000,
    inventory: [
      {
        id: "sp-24-1",
        name: "Propeller Shaft",
        sku: "PROP-SHFT",
        category: "Propulsion",
        quantity: 1,
        minLevel: 0,
        unit: "Pcs",
        location: "Store",
        lastUpdated: "2024-01-01",
      },
    ],
  },
  {
    id: "25",
    number: "RG-SEMI-02",
    name: "Rig Naga Utara",
    category: "Offshore Rig",
    subType: "Semi-Sub",
    location: "East Natuna",
    coordinates: { lat: 4.2, lng: 108.5 },
    history: [
      { lat: 4.2, lng: 108.5 },
      { lat: 4.22, lng: 108.52 },
    ],
    dailyRate: 2000000000,
    status: "Verification",
    health: 100,
    csmsScore: 98,
    incidentCount: 0,
    daysSinceIncident: 0,
    yearBuilt: 2022,
    manufacturer: "Daewoo",
    ownerType: "Foreign",
    certification: "Pending",
    capacityString: "5000 ft WD",
    specs: {
      ratedHP: 3000,
      drillingDepth: 30000,
      waterDepth: 5000,
      quartersCapacity: 150,
      variableDeckLoad: 8000,
      wellControl: {
        bopStack: "18-3/4 15k",
        diverter: "Hydril 500",
        chokeManifold: "15k PSI",
        accumulatorUnit: "3000 PSI",
      },
    },
    co2Emissions: 0,
    totalEmissions: 0, // Brand new
    nextMaintenanceDate: "2025-06-01",
    mtbf: 10000,
    inventory: [], // New rig, inventory not fully loaded yet (Demo scenario)
  },
];

export const zones: Zone[] = [
  {
    id: "z1",
    name: "Zona Merah (Natuna)",
    coordinates: { lat: 4.8, lng: 108.0 },
    radius: 100000, // meters
    color: "#ef4444", // red
    type: "danger",
  },
  {
    id: "z2",
    name: "Area Konservasi Karang",
    coordinates: { lat: -5.8, lng: 106.5 },
    radius: 50000,
    color: "#3b82f6", // blue
    type: "safe",
  },
];

export const requestsData: QuotationRequest[] = [
  {
    id: "ME-2024-001",
    date: "2024-01-15",
    assetName: "Rig Darat 2000 HP",
    category: "Onshore Rig",
    status: "Approved",
    hps: "IDR 45.000.000.000",
    kkksName: "Pertamina Hulu Rokan",
    contactName: "Budi Santoso",
    projectName: "Pengembangan Lapangan Minas",
    dateFrom: "2024-06-01",
    dateTo: "2024-12-31",
    techStatus: "Valid",
    techNotes: "Spesifikasi sesuai kebutuhan operasi.",
  },
  {
    id: "ME-2024-002",
    date: "2024-02-10",
    assetName: "AHTS Vessel 80T BP",
    category: "Kapal",
    status: "Pending",
    hps: "IDR 12.000.000.000",
    kkksName: "Medco Energi",
    contactName: "Siti Aminah",
    projectName: "Logistik Natuna",
    dateFrom: "2024-05-01",
    dateTo: "2024-08-01",
  },
  {
    id: "REQ-2024-003",
    date: "2024-03-01",
    assetName: "Drillship 10000ft WD",
    category: "Offshore Rig",
    status: "Review",
    hps: "USD 250,000 / day",
    kkksName: "ENI Indonesia",
    contactName: "Marco Polo",
    projectName: "Deepwater Exploration",
    dateFrom: "2024-08-01",
    dateTo: "2024-12-01",
  },
];

export const tendersData: Tender[] = [
  {
    id: "TDR-2024-001",
    name: "Penyewaan Rig Darat 2000 HP - WK Rokan",
    description: "Penyediaan Rig Darat unntuk pengeboran sumur pengembangan.",
    createdDate: "2024-01-20",
    items: ["ME-2024-001"],
    status: "Published",
    totalValue: 45000000000,
    bids: [
      {
        id: "BID-001",
        tenderId: "TDR-2024-001",
        vendorId: "v-001",
        vendorName: "PT. Samudra Merah Putih",
        amount: 44000000000,
        submittedDate: "2024-01-25",
        technicalScore: 88,
        commercialScore: 92,
        status: "Shortlisted",
        documents: [],
      },
    ],
  },
  {
    id: "TDR-2024-002",
    name: "Pengadaan Vessel AHTS - Natuna Area",
    description: "Kapal penunjang operasi lepas pantai.",
    createdDate: "2024-02-15",
    items: ["ME-2024-002"],
    status: "Draft",
    totalValue: 12000000000,
    bids: [],
  },
  {
    id: "TDR-2023-099",
    name: "Maintenance Turbin Gas",
    description: "Jasa pemeliharaan rutin turbin.",
    createdDate: "2023-11-10",
    items: [],
    status: "Review",
    totalValue: 5000000000,
    bids: [
      {
        id: "BID-099-1",
        tenderId: "TDR-2023-099",
        vendorId: "v-003",
        vendorName: "Deepsea Drilling Intl",
        amount: 4800000000,
        submittedDate: "2023-11-20",
        technicalScore: 70,
        commercialScore: 85,
        status: "Pending",
        documents: [],
      },
    ],
  },
  {
    id: "TDR-2023-088",
    name: "Supply Chain Ps. 2",
    description: "Logistik rutin area Jawa.",
    createdDate: "2023-10-01",
    items: [],
    status: "Closed",
    totalValue: 8000000000,
    bids: [],
  },
];

export const assessmentData: any[] = [
  {
    id: "ASM-2024-001",
    title: "Asesmen Pasar Pipa OCTG",
    status: "Tersimpan",
    createdAt: "2024-01-10",
    createdBy: "Procurement Mgr",
    filters: {
      category: "Kapal",
      startDate: "2024-01-01",
      endDate: "2024-12-31",
      minYear: 2015,
      minCapacity: 100,
    },
    candidates: [],
  },
  {
    id: "ASM-2024-002",
    title: "Market Survey for Drillships",
    status: "Konsep",
    createdAt: "2024-03-05",
    createdBy: "Exploration Team",
    filters: {
      category: "Offshore Rig",
      startDate: "2024-06-01",
      endDate: "2024-12-01",
      minYear: 2010,
      minCapacity: 10000,
    },
    candidates: [],
  },
];
